### ISSUE TITLE
Apply Software Engineering Practices

### ISSUE THREAD

**Issue by krother** [ktroutman/Twitter_Mongo_Proj#2]
- [x]  version control
- [x]  coding style (pylint)
- [x]  automated tests (pytest)
- [x]  continuous integration (Travis)
- [x]  documentation (Sphinx)
- [x]  build a package (distutils)
- [x]  deploy (fabric)
- [x]  requirements.txt

**Comment by krother** [comment]
I'd be happy to work with someone on pylint

**Comment by abyz0123** [comment]
adding @ErikMann
